Module 1: Html CSS Mobile version skeleton
alvinlouis29/My-Portfolio-Website pull request #1
Opened 2022-03-18 22:36 UTC by alvinlouis29

##The goal of the project is to understand how to parse a Figma design to create a User Interface for My-Portfolio-Website.
##I have used flexbox to place the elements on the page and also used a background to enhance the look and feel of the site.

2022-03-18 23:58 UTC, smunozmo requested changes
Hi @alvinlouis29, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>

## Highlights 👏 

- Great work using the right GitHub Flow.
- Commits are descriptive, good work.

## Required Changes ♻️

- [ ]  Your README file has all the required parts but it is missing your personal information, I strongly recommend you to update the information to avoid a review invalidation in the future, this file is very important for people to know what your project is about.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 23:58 UTC, smunozmo commented on index.html
> +        <h2 class="hidden">Hero</h2>
- [ ] Great job with the headings, however, this line is unnecessary, it would be better to remove it as this would make yyour code cleaner.

2022-03-18 23:58 UTC, smunozmo commented on index.html
> +                </ul>
- This is perfect.

2022-03-18 23:58 UTC, smunozmo commented on style.css
> +  background-image: url(./images/one.png);
- [ ] Your design is looking great, but this is the desktop version background, please use the mobile version one.

2022-03-18 23:58 UTC, smunozmo commented on index.html
> +            </div>
- [ ] This heading is almost done, I strongly suggest adding more space between the subtitle and the paragraph:

Template:
![Captura de pantalla 2022-03-18 a la(s) 6 45 37 p  m](https://user-images.githubusercontent.com/83717285/159097814-4d4a7625-c2ae-43db-912e-f97fdca82d61.png)

Your design:
![Captura de pantalla 2022-03-18 a la(s) 6 45 28 p  m](https://user-images.githubusercontent.com/83717285/159097824-5713438b-47ef-48a8-8fb4-090aa5659fe8.png)

2022-03-19 00:03 UTC, smunozmo reviewed
You are almost there!

2022-03-19 06:55 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @alvinlouis29 , 

Your project is complete!  You have implemented well all the requested things asked by the previous reviewer. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Clean code.
:heavy_check_mark: Well implemented Figma design.

### Optional suggestions :arrow_down_small: 

- [ ] As your previous reviewer didn't ask it mandatory, I kept it optional. You have a horizontal scrollbar on your page. Please fix it. You can use [CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries.asp) for your mobile version. It will make your website responsive. :+1: 

https://user-images.githubusercontent.com/70483835/159111015-6986a948-7860-47bf-a760-72498eeb596a.mp4

- [ ] The commit message should be written in the imperative tense. `Ex: "Fix bug" instead of "Fixed bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

- [ ] For readability, please add two spaces of indentation. Do not use the tab key. You did it throughout your code in the `HTML` file. Please fix it. [For the HTML & CSS best practices, ](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)we should follow the rules.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-19 08:11 UTC, merged