Module 1: Middle section My Portfolio Website
alvinlouis29/My-Portfolio-Website pull request #2
Opened 2022-03-19 12:44 UTC by alvinlouis29

##The main objective of this project is to understand how to parse a Figma design to create a UI using Flexbox and CSS Grid to ##place elements in the page.

2022-03-19 17:38 UTC, OLIPLICHE requested changes
Hi @alvinlouis29 , 

Good job so far!
There are some issues that you still need to work on to get your project approved, but you are almost there!

## Highlights Good Points: 👍
✔️ No linters error.
✔️ Github flow used properly.
✔️ Pull Request has a descriptive title telling you what changes are inside.


## Required Changes ♻️

- [ ] Please Remove the `Live Demo` section in your ReadMe. It is not important for now.

- [ ]  CHECK THE COMMENTS UNDER THE REVIEW⬇..

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider:**
- Pull Request should have a short summary describing introduced changes in more detail.
- Please beautify your HTML code before pushing it to GitHub, I strongly recommend that.  Otherwise, your work will be considered **unprofessional**.

- [x] **Professional**:

- [x] ![id1](https://user-images.githubusercontent.com/63972670/159131900-b1da7f39-1f7f-4e87-9fbb-4bfbeea509ae.JPG)

- [x] **Not Professional**

- [x] ![id2](https://user-images.githubusercontent.com/63972670/159132013-ff52e50c-da74-49a8-9422-a403d781500c.JPG)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 17:38 UTC, OLIPLICHE commented on index.html
> +   <div class="open"><a href="#">See Project</a></div>
- [x] The button `See project` follows the button styling: Active, Hover, and Pressed (see design).
- [ ] 
![image](https://user-images.githubusercontent.com/63972670/159130408-23a8a495-aefa-4b2b-847b-0267c4286405.png)

2022-03-19 17:38 UTC, OLIPLICHE commented on index.html
> +  <div class="cards">
- [ ] Please Follow the[ Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988) and add what is missing in your design.   

- [ ] **Original Design**

![see1](https://user-images.githubusercontent.com/63972670/159130787-a05d25e8-5665-4f8b-87eb-e9fa5c2a7587.JPG)

- [ ] **Your Design**

![see2](https://user-images.githubusercontent.com/63972670/159130825-476d69c2-d1bf-4f6f-a095-dc6d6e042702.JPG)

2022-03-19 17:38 UTC, OLIPLICHE commented on index.html
> +  <div class="resume"><a href="#">Get My Resume</a></div>
- [ ] Please The button `Get my resume` follows the button styling: Active, Hover, and Pressed (see design)

![image](https://user-images.githubusercontent.com/63972670/159131134-f8c13d78-9330-408f-b0cf-cb62a9959614.png)

2022-03-19 17:38 UTC, OLIPLICHE commented on index.html
> +  <h1>Frameworks</h1>
- [ ] Please the technology categories ("Languages", "Frameworks" and "Skills") are in a `<ul>`, each of them in a `<li>`

2022-03-20 01:38 UTC, smunozmo approved these changes
Hi @alvinlouis29, 👋 

Good job making all the required changes, your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 

Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-20 02:24 UTC, merged