Add Form and footer
alvinlouis29/My-Portfolio-Website pull request #4
Opened 2022-03-23 17:51 UTC by acolombo1

Add form-section and footer, and style all to look like the figma design

2022-03-23 19:42 UTC, prolajumokeoni reviewed
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-24 00:16 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️

Hi Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![SoCloseKeeganMichaelKeyGIF](https://user-images.githubusercontent.com/50941074/159817133-188e50a5-8c73-4b3b-8993-50b629e09ec6.gif)


## Highlights
✔️ Linters are running fine
✔️ README is professional
✔️ Good Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 00:16 UTC, AmaduKamara commented on index.html
> +        </li>
- [ ] Kindly add the `required` attribute on the `textarea` field to stop the user from sending an empty message for that field. This attribute is there to activate the validation upon submission of the form. For this project, you were required to have it set. Please fix that. 👍

2022-03-24 00:16 UTC, AmaduKamara commented on style.css
> +}
- [ ] Please add the background image for this section to match your design with the Figma one
- Your Design
![image](https://user-images.githubusercontent.com/50941074/159816517-24e80865-e741-450b-9fa0-fb0750d8f4ab.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/50941074/159816596-f9b488ca-9db4-4e9c-ad24-5e49eba8f080.png)

2022-03-24 01:55 UTC, Rustamxon7 approved these changes
## Hello @acolombo1 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-24 01:57 UTC, merged